### ISSUE TITLE
Histogram exploded the memory.

### ISSUE THREAD

**Issue by ethanluoyc** [lanpa/tensorboard-pytorch#1] opened 2017-07-16 17:53 UTC
Hi,

thank you for providing this library. Some problems that I came across today.

If I try to make a histogram out of the weights of some module, it is possible to explode the number of bins and consume an extremely large amount of memory. The problem due to this line https://github.com/lanpa/tensorboard-pytorch/blob/master/tensorboard/summary.py#L118. The argument `bins` is never used, and as a results `auto` is used in `np.histogram`, which would produce `bin` that is as large as 66618527586 (see attachment for an example of a bad weight matrix)

I am not sure what the preconditions for the HistogramProto are, but using the bins argument and passing it into `make_histogram` would solve the problem.

[x.npy.zip](https://github.com/lanpa/tensorboard-pytorch/files/1151208/x.npy.zip)

**Comment by elbamos** [comment] 2017-07-16 18:25
I've been experiencing an issue on OS X where I get a freeze up periodically when writing lots of histograms. I haven't traced it to a source yet which is why I didn't post an issue, but maybe it's related.

**Comment by lanpa** [comment] 2017-07-16 18:27
The `bins` argument is overwritten intentionally:) Because I am wondering why tensorflow has a fixed binning scheme. I also tested your weight matrix under ipython with `np.histogram(x, 'auto')` and it also freezes my console. So I think there is a good reason why using fixed bins. BTW, By passing the `bins` parameter without overwriting it, you are instead using the tensorflow binning method. You may have a look at https://github.com/lanpa/tensorboard-pytorch/blob/master/tensorboard/writer.py#L212 . This will be fixed in next version. Thanks.

**Comment by ethanluoyc** [comment] 2017-07-16 23:13
Yeah I was wondering why everything slows down suddenly and thought it might be a problem with pytorch not freeing the memory for some storage :) some digging led to this finding.
________________________________

**Comment by lanpa** [comment] 2017-07-17 08:22
https://github.com/numpy/numpy/search?q=histogram&type=Issues

I think the root cause is `np.histogram`. If problem continues, maybe we need to implement our own version.

**Closed by lanpa** 2017-07-17 08:22 UTC
